# APP NAME
spring:
  application:
    name: processingplatform-local
#  DATABASE CONFIGURATION
  data:
    mongodb:
      host: localhost
      port: 27017
      database: processingplatform
      repositories:
        type: auto
logging:
  level:
    org:
      springframework:
        security: INFO



